[package]
name = "neural"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
candle = "0.0.0"
candle-core = "0.3.0"
candle-nn = "0.3.0"
serde = "1.0.190"
